### ISSUE TITLE
what the frick dev 

### ISSUE THREAD

**Issue by TheLDB** [idkwuu/RatioTerminal#7]
so i was just *casually* ratioing people in my favorite discord peroxaan studios (https://discord.gg/TN9YwgnpUY) when my (no longer) favorite bot decided to break on me. how are you gonna give me a thumbs down and a checkmark???????

bad dev please fix you need to fix this. i dont care if it takes 24 hours, you oepn sourced it this is your fault fix now you "dev" if i can even call you that

![Screen Shot 2021-11-06 at 11 30 12 PM](https://user-images.githubusercontent.com/29960599/140633631-10c21f1f-e17d-4808-9db2-037a1d004014.png)

**Comment by idkwuu** [comment]
![ratiodeclined](https://user-images.githubusercontent.com/42050584/140654451-830eac81-752b-4ddc-af54-9e4aca2c151a.png)
